Repository mostlygeek/llama-swap, pull requests merged in 2025-05, with the labels that each got.

#115 Improve content-length handling
  misc/simple-responder/simple-responder.go
  proxy/proxymanager.go
  proxy/proxymanager_test.go
Labels: bug, enhancement

#117 Automatic Port Numbers
  README.md
  proxy/config.go
  proxy/config_test.go
Labels: enhancement

#123 Add a concurrency limit to Process.ProxyRequest
  proxy/config.go
  proxy/process.go
  proxy/process_test.go
Labels: enhancement

#126 Change /unload to not wait for inflight requests (#125)
  llama-swap.go
  proxy/process.go
  proxy/process_test.go
  proxy/processgroup.go
  proxy/processgroup_test.go
  proxy/proxymanager.go
  proxy/proxymanager_test.go
Labels: enhancement

#127 Improve testing around using SIGKILL
  Makefile
  misc/simple-responder/simple-responder.go
  proxy/helpers_test.go
  proxy/process.go
  proxy/process_test.go
  proxy/proxymanager_test.go
Labels: enhancement

#129 Prevent StateFailed after SIGKILL
  proxy/process.go
Labels: bug

#131 Fix content length being incorrect when useModelName is used
  proxy/proxymanager.go
Labels: bug

#134 Fix #133 SanitizeCommand removes comments
  proxy/config.go
  proxy/config_posix_test.go
  proxy/config_windows_test.go
Labels: bug

#136 Add stopCmd to model configuration
  README.md
  proxy/config.go
  proxy/config_windows_test.go
  proxy/process.go
  proxy/process_stop.go
  proxy/process_stop_windows.go
  proxy/process_test.go
Labels: enhancement

#137 Allow Failed -> Stopping Process state change
  proxy/process.go
  proxy/proxymanager.go
Labels: enhancement
